module.exports = {
    company_name: 'Technical of RSP Groups',
    legal_name: 'Technical of RSP Groups',
    short_name: 'Technical of RSP Groups',
    site_url: process.env.SITE_URL || 'https://trsp-group-website.onrender.com',
    logo_path: '/img/logo.png',
    icon_path: '/img/navbar-mark.png',
    location: 'Chikkamagaluru, Karnataka',
    address: 'Near Water Tank, Teguru',
    postal_code: '577101',
    gst: '[Your GST Number]',
    email: 'info@trspgroups.com',
    phone_display: '+91 7795183739',
    phone_href: '+917*******39',
    whatsapp_href: 'https://wa.me/917*******39',
    default_description: 'Technical of RSP Groups delivers research-driven software, digital products, and technology solutions from Chikkamagaluru, Karnataka.',

    // Page headings/kickers/descriptions below are all admin-editable via
    // Site Info -> Page Text. These are just the defaults shown until an
    // admin overrides them.
    home_hero_kicker: 'Research-Driven Technology Partner',
    home_hero_title: 'Build smarter software, digital products, and business-ready systems.',
    home_hero_description: 'We help organizations move from concept to launch with modern engineering, better user experience, secure delivery, and practical product strategy.',
    home_services_kicker: 'What We Do',
    home_services_heading: 'Our Services',
    home_services_description: 'Technical of RSP Groups combines engineering, analytics, cybersecurity, and product thinking to deliver dependable solutions that are easy to adopt and ready to scale.',
    home_about_kicker: 'About Us',
    home_about_heading: 'Technology delivery backed by clear research and practical execution.',
    home_research_kicker: 'Research Focus',
    home_research_heading: 'Our Research Verticals',
    home_research_description: 'We explore scalable architecture, product R&D, and analytics capabilities that strengthen software delivery and decision-making.',
    home_testimonials_kicker: 'Client Trust',
    home_testimonials_heading: 'What Clients Say',
    home_testimonials_description: 'We aim to be consistent, collaborative, and dependable across every engagement.',
    home_upcoming_kicker: "What's Next",
    home_upcoming_heading: 'Upcoming Features',
    home_upcoming_description: 'A look at what our team is actively building next.',
    home_hero_btn1_label: 'Get Quote',
    home_hero_btn2_label: 'Call Now',
    home_about_paragraph2: 'We focus on strong fundamentals: clean architecture, secure implementation, measurable outcomes, and collaboration that keeps projects moving forward.',
    home_about_mission_title: 'Mission',
    home_about_mission_text: 'Deliver dependable software solutions with clarity, trust, and long-term value.',
    home_about_approach_title: 'Approach',
    home_about_approach_text: 'Combine research, product thinking, and engineering discipline to solve real business problems.',
    home_about_btn_label: 'Learn More',

    services_hero_kicker: 'Our Expertise',
    services_hero_title: 'Services designed to move ideas into reliable products.',
    services_hero_description: 'From engineering delivery to analytics, security, and product scale-up, Technical of RSP Groups helps businesses build with clarity and confidence.',
    services_offer_kicker: 'What We Offer',
    services_offer_heading: 'Our Services',
    services_offer_description: 'Each service is shaped to reduce delivery friction, improve visibility, and give your team a stronger foundation for growth.',
    services_process_kicker: 'How We Work',
    services_process_heading: 'A simple process with strong execution.',
    services_process_description: 'We keep communication clear, delivery structured, and technical decisions aligned with business goals.',
    services_process_card1_title: 'Discover',
    services_process_card1_text: 'We understand your goals, users, constraints, and technical priorities before recommending the right path.',
    services_process_card2_title: 'Design & Build',
    services_process_card2_text: 'We shape the architecture, user flows, and implementation plan, then deliver in focused, testable increments.',
    services_process_card3_title: 'Improve & Scale',
    services_process_card3_text: 'We refine performance, strengthen security, and support the next stage of growth after launch.',

    about_heading: 'Research-led technology support for businesses building what comes next.',
    about_paragraph2: 'Our work combines software engineering, research thinking, security awareness, and delivery discipline so that every engagement stays practical, measurable, and aligned with business goals.',
    about_mission_title: 'Mission',
    about_mission_text: 'Deliver digital solutions that create long-term value through quality, trust, and clear communication.',
    about_vision_title: 'Vision',
    about_vision_text: 'Become a trusted technology partner for organizations across Karnataka and beyond.',
    about_team_title: 'Team',
    about_team_text: 'Support clients with focused engineering, collaborative execution, and dependable follow-through.',
    about_focus_title: 'Focus',
    about_focus_text: 'Turn ideas into usable systems that are secure, maintainable, and ready to scale.',

    contact_heading: 'Contact Us',
    contact_subheading: 'Get in touch with Technical of RSP Groups. We are here to help.',
    contact_form_heading: 'Get in Touch',
    contact_form_name_placeholder: 'Your Name',
    contact_form_email_placeholder: 'Your Email',
    contact_form_phone_placeholder: 'Phone Number',
    contact_form_service_placeholder: 'Select a service',
    contact_form_message_placeholder: 'Your Message',
    contact_form_submit_label: 'Send Message',
    contact_location_heading: 'Our Location',
    contact_map_embed_url: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15592.843846892315!2d75.767748!3d13.315308!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bbb5e6c5d0b5b3d%3A0x6f0b5e6c5d0b5b3d!2sChikkamagaluru%2C%20Karnataka!5e0!3m2!1sen!2sin!4v1708000000000',

    store_hero_kicker: 'Store',
    store_hero_heading: 'Packages & Products',
    store_hero_description: 'Purchase a package directly online, or contact us for a custom quote.',

    nav_home_label: 'Home',
    nav_services_label: 'Services',
    nav_store_label: 'Store',
    nav_contact_label: 'Contact',
    nav_about_label: 'About',
    nav_login_label: 'Login / Sign Up',
    nav_logout_label: 'Logout',

    footer_contact_heading: 'Contact Us',
    footer_terms_label: 'Terms & Conditions',
    footer_privacy_label: 'Privacy Policy',
    footer_rights_text: 'All Rights Reserved.',

    welcome_enabled: 'true',
    welcome_heading: 'Welcome to Technical of RSP Groups',
    welcome_tagline: 'Research-driven technology, engineered with care.',
    welcome_button_label: 'Enter Site',
    welcome_duration_seconds: '6',

    routes: {
        home: '/',
        about: '/about',
        services: '/services',
        contact: '/contact',
        'software-development': '/software-development',
    },

    research_verticals: [
        {
            id: 'research1',
            title: 'System Architecture',
            summary: 'Designing scalable, resilient, and AI-native frameworks for complex distributed systems, enabling efficient training and deployment of large-scale AI models.',
            areas: [
                'Scalable Distributed Systems',
                'Cloud-Native & Microservices Architecture',
                'Fault-Tolerant & High-Availability Design',
                'AI-Optimized Infrastructure',
                'Edge Computing Frameworks',
            ],
        },
        {
            id: 'research2',
            title: 'Product R&D',
            summary: 'Rapid prototyping, iterative testing, and AI-accelerated development of high-precision, user-centric products, from concept to market-ready solutions.',
            areas: [
                'AI-Driven Prototyping',
                'User-Centered Product Design',
                'Agile Development Cycles',
                'Precision Engineering & Testing',
                'Market-Ready Innovation',
            ],
        },
        {
            id: 'research3',
            title: 'Data Analytics',
            summary: 'Advanced AI-driven analytics for extracting actionable insights, predicting system behavior, and optimizing performance at scale.',
            areas: [
                'Predictive Modeling',
                'Real-Time Data Processing',
                'Machine Learning Insights',
                'Performance Optimization',
                'Big Data Analytics',
            ],
        },
    ],

    testimonials: [
        { quote: 'Outstanding service and professionalism from Technical of RSP Groups!', author: 'Client Name, Company' },
        { quote: 'Highly recommended for quality and timely delivery.', author: 'Another Client' },
        { quote: 'Excellent partner for all our needs - reliable and innovative.', author: 'Third Client' },
    ],

    software_portfolio: [
        { title: 'E-Commerce Platform', description: 'Full-stack React + Node.js app with payment integration', image: '/img/portfolio-ecommerce.svg' },
        { title: 'Inventory Management System', description: 'Enterprise ERP with real-time tracking', image: '/img/portfolio-inventory.svg' },
        { title: 'AI-Powered Dashboard', description: 'Predictive analytics web app', image: '/img/portfolio-dashboard.svg' },
    ],
};
